### PR TITLE
[apps/code] Toolbox improvement

### LINKED ISSUE #109: Do not close the python toolbox when module function prefix is selected
I would like the toolbox not to be closed when I select the "module function prefix" option like [here](https://imgur.com/a/QvqC78q) with the math module so that I'm not forced to re-open the toolbox to write a function.

### PR DESCRIPTION
**Pull request by devdl11**
Solving issue 109

### CODE REVIEW

**Comment by Lauryy06** [comment]
This fix can be very strange for the user if he dont know the feature and can't close the toolbox. I think that the way I proposed is better, and it's also easy to implement.

**Comment by devdl11** [comment]
> This fix can be very strange for the user if he dont know the feature and can't close the toolbox. I think that the way I proposed is better, and it's also easy to implement.

I tried to use the method " isShiftActive()" of Ion::Events (file: ion/src/shared/event_modifier.cpp) but it didn't work ( I think the exe/ok event is cancelling the "shift" before being handeled by the toolbox).
By the way, the toolbox implementation gave me headaches on how it's split on severals files and how it's managed by the system... I understand now the "Good Luck Have Fun" of @RedGl0w ^^

Nevertheless, I agree with you that it can surprise at first the user. But is it worth to review now the entire toolbox system ? (If I didn't miss of course another way of getting the shift status)

**Comment by Lauryy06** [comment]
I think it's possible by adding the events ShiftOk and ShiftEXE and intercepting them in handleEvent methods.
If you want [this](https://github.com/Omega-Numworks/Omega/pull/320) add a new shift-specific event.

**Comment by Lauryy06** [comment]
I fix it in a (I think) better way in e575ffc7ce3ce0b5c3091546cf0eab2d73ecec07.

**Pull request closed without merging**
