### PR TITLE
Casio fx-CG series port

### PR DESCRIPTION
**Pull request by Heath123**
There are a few more thing left to finish, but I think it's more or less in a mergable state now, but I need to update the icon and name of the built g3a file from Omega to Upsilon

### CODE REVIEW

**Comment by Heath123** [comment]
Looks like this causes some issues when building for the Numworks calculator, I'll have to fix that

**Comment by Yaya-Cout** [comment]
Can you add it to the CI ? (You can look how it is done for the N0110 target, this is the simplest)

**Comment by Heath123** [comment]
> Can you add it to the CI ? (You can look how it is done for the N0110 target, this is the simplest)

Yes, I'll try doing that

**Comment by Heath123** [comment]
> Can you add it to the CI ? (You can look how it is done for the N0110 target, this is the simplest)

I've done it, I think

**Comment by Heath123** [comment]
OK, I think it's mergable (or at least reviewable) now

Things I need to work on still, but maybe in a different PR:
- Persistent saving of things like settings (I think the official simulators don't have this so it's probably fine for now)
- Some things are cut off at the bottom in the distribution and atomic apps
- ~~Sleep mode~~ Done
- Line drawing seems to be slow as it uses floating point
- Gamma correction is slow and I'm not sure if the magnifier works properly
- I'm not sure if external apps can worl
- The date/time can be read but not set
- Battery level reporting
- Maybe put something for the serial number and FCC ID
- The key mapping can be improved slightly
- Clipboard integration

**Comment by Heath123** [comment]
Oh, it looks like I forgot to `git add` a file

**Comment by Heath123** [comment]
The CI build should work now and I also fixed the web build (or should that be a separate PR?)

Should it only build when triggered like on the 3DS, iOS and Mac OS?

Also the size of the cache might be a bit big, I can probably trim it down though

**Comment by Yaya-Cout** [comment]
Can you revert the changes to the Web CI ? (I have a fix in local that allow to build using the latest Emscripten version).
For the CI build settings, I don't know if you need to add it. If it's really needed, I can add it later (it is better to test if every target to see if it is still working that never testing it)

**Comment by Heath123** [comment]
I’ve reverted it

**Pull request merged**
