### PR TITLE
set_led support

### PR DESCRIPTION
**Pull request by Oreig403**
I created a function called set_led to change the led color.
I arranged myself so this function doesn't work in Exam Mode to prevent cheating.

### CODE REVIEW

**Comment by Oreig403** [comment]
wow I think I did my pull request wrong

**Comment by Oreig403** [comment]
it wants to add 450 files but I changed 5

**Comment by Oreig403** [comment]
I'm gonna remake a pull request

**Comment by Lauryy06** [comment]
So I close it.

**Pull request closed without merging**
