### PR TITLE
Dark Theme changes

### PR DESCRIPTION
**Pull request by Syycorax**
Changed syntax Highlighting, line number background color and toolbox colors

### CODE REVIEW

**Comment by hugo-b-r** [comment]
Maybe, you could also add this icon for reader:
reader_icon

**Comment by Syycorax** [comment]
@lemoustachu Done, can't check today if it's working, but named the file with the name found in icons.json. If someone could check, it would be great!

**Comment by hugo-b-r** [comment]
@Syycorax tested and works well with binpack.

**Comment by Lauryy06** [comment]
Can you also update the epsilon dark theme ?

**Comment by Syycorax** [comment]
Updated epsilon dark, icons would still need to be changed, and the reader icon updated to match epsilon colors but i can't do neither of those things

**Comment by Lauryy06** [comment]
We will to automate build of icons, so you don't need to do it for the moment. Thanks for the pull request, I'm going to merge it.

**Pull request merged**
