### PR TITLE
set_led support

### PR DESCRIPTION
**Pull request by Oreig403**
I created a function called set_led to change the led color.
I arranged myself so this function doesn't work in Exam Mode to prevent cheating.
The syntax is set_led(color)

### CODE REVIEW

**Comment by Lauryy06** [comment]
Sorry but I can't merge this for obvious reasons. The problem is not to disable this function in exam mode, it is that it can be used to simulate the exam mode.

**Comment by Oreig403** [comment]
Yes but the function cannot be used out of the python program

**Comment by Lauryy06** [comment]
For example, you can't distinguish a calculator in exam mode from a calculator returned on a table with a python script that makes the led blink.

**Comment by Oreig403** [comment]
Ok sorry to disturb you

**Comment by Lauryy06** [comment]
You're not disturbing, but that pull request was just a little awkward. There are better things to do with python!

**Pull request closed without merging**
