### PR TITLE
Make the height of variables and toolbox view the same as additional results view

### PR DESCRIPTION
**Pull request by LukasMFR**
Simple but makes the height of variables and toolbox view the same as additional results view like recent versions of Epsilon.

### CODE REVIEW

**Comment by Yaya-Cout** [comment]
Why are you using NumWorks's commits ?

**Comment by LukasMFR** [comment]
I don't know, on the Discord server they said what I did was ok. I never did that on GitHub, so I had no idea what I was really doing.

**Comment by Lauryy06** [comment]
Indeed, there are too many changes in this pull request.

**Comment by Lauryy06** [comment]
Indeed, there are too many changes in this pull request.

**Comment by LukasMFR** [comment]
So what do I need to do ?
In this case it's just changing one variable of one single file so maybe I could just open an issue, tell you where it is and what to change it to ?
GitHub is hard sometimes just for simple things.

**Comment by Lauryy06** [comment]
Yeah, I will do it myself. Is it the value in metric.h that I must modify ?

**Comment by LukasMFR** [comment]
Yes exactly after testing 15 seems to be good (it's the same as additional results view)

**Comment by Lauryy06** [comment]
I just did it, thanks for the pull request even though it was not merged.

**Comment by LukasMFR** [comment]
You're welcome ! I think I found the issue, I had to create a "branch".

**Comment by Lauryy06** [comment]
Yes, but don't worry, it is by doing that we learn.

**Pull request closed without merging**
