### PR TITLE
Allow user to stop graph rendering

### PR DESCRIPTION
**Pull request by Yaya-Cout**
A simple code to allow the user to stop graph rendering.

### CODE REVIEW

**Comment by Lauryy06** [comment]
I think this can be implemented better, it can be strange for the user if he stop drawing the function and he can still navigate in the window. Can you make the return leave the graph window instead ?

**Comment by LemmusLemmus** [comment]
@Lauryy06 Whilst I agree that it would be strange for the user if they could still navigate the window, it can also make sense sometimes. Let's say the user is graphing a very computationally heavy function and they are only interested in a portion of it. They can in such a case stop the graphing once they are satisfied with the graph and for example find the location of a minimum value.

I think a better solution would be to display something that indicates where the graph rendering stopped (for example a cross at the end of the graph). It might alternatively be easier to program the calculator to just display a red text saying something along the lines of "graphing aborted".

This of course depends on how well the built-in plot options and navigation works with an incomplete graph. If it results in unexpected behavior the graph window should probably be exited.

**Comment by Lauryy06** [comment]
If the user wants to study only a part of the function, he can use the associated setting (by clicking on the function name in the first menu). 
I don't know if you have tested this, but moving a cursor on an invisible curve is really strange, and it is not in the spirit of the firmware to let the user do strange things like this one.

**Comment by FaustinM** [comment]
Can you provide a example of a heavy computing function ? Thanks! :)

**Comment by Yaya-Cout** [comment]
For the heavy computing function, I use `random()` for testing

**Comment by Lauryy06** [comment]
But isn't it possible to make the user leave the graphical view and go back to the list of functions when he makes a return? Even with a message, I think it's just horrible from an UX point of view to navigate through an unfinished graph. And nobody will use the return to draw only a part of the graph, it is much easier to use the interval parameter.

**Comment by Yaya-Cout** [comment]
So I close this pull request?

**Comment by Lauryy06** [comment]
I think that this pull request starts from a good idea, but that in the state it is not finished. You can continue it or abandon it, the choice is yours.

**Comment by Yaya-Cout** [comment]
I will close it because I don't know how to finish it correctly.

**Pull request closed without merging**
