### PR TITLE
[apps/code] Remove base python script and add mathsup.py

### PR DESCRIPTION
**Pull request by Mino1289**
The purpose of this PR is to:
- [x] Remove the basic python scripts.
- [x] Add mathsup.py, a utility containing a lot of useful functions (which are difficult to implement in the software)

### CODE REVIEW

**Comment by FaustinM** [comment]
Why remove all the base python scripts ?

**Comment by Mino1289** [comment]
They're useless (for me ans the usage I have of the calculator)

**Comment by FaustinM** [comment]
> They're useless (for me ans the usage I have of the calculator)

But it's a good test, it's a python boilerplate, and if we remove them we have more conflict with epsilon (i don't see any real reason beside the utility of the scripts)

**Comment by Mino1289** [comment]
> > They're useless (for me ans the usage I have of the calculator)
> 
> But it's a good test, it's a python boilerplate, and if we remove them we have more conflict with epsilon (i don't see any real reason beside the utility of the scripts)

Maybe the next step is to implement all the mathup functions in the base firmware

**Review by Lauryy06 — CHANGES_REQUESTED** [review]
I agree that the default scripts are useless, but I think it is better to try to implement the functions of mathsup.py in poincare rather than in another default script. 
If you want you can open an issue to ask for this, in the meantime you can remove mathsup.py from the default scripts.

**Pull request merged**
