### PR TITLE
 [apps/code] Increase of number of functions loaded in the variable box

### PR DESCRIPTION
**Pull request by Mino1289**
Increase of number of variables loaded in the variable box.

Now you can :
- Load up to 128 functions (instead of 32 previously) in the variable box.
- Load the functions (in the limit of 128) of up to 8 files (instead of 3 previously) in the variable box.

### CODE REVIEW

**Review by FaustinM — COMMENTED** [review]
Why their are this limits

**Comment by Mino1289** [comment]
> Why their are this limits

As the comments said it's an arbitrary limit. I tested it for a long time and worked fine.

**Comment by FaustinM** [comment]
Did you do some test with 128 functions ?

**Comment by Mino1289** [comment]
> Did you do some test with 128 functions ?

I didn't try with 128 functions, but with at least more than 32, that's why I made the change at the time. 
You can try with a good amount of functions here : 
- Python File [mathsup.py](https://github.com/Mino1289/Python-for-Numworks/blob/main/scripts/maths/mathsup.py)
- Sending to the calculator with [Numworks website](https://my.numworks.com/python/mino-1289/mathsup)


PS: With E16 threat, maybe not try to use the Numworks website. For me it was ok but maybe that changed

**Comment by FaustinM** [comment]
I think it's a must have to verify if everything works with 128 functions

**Comment by Lauryy06** [comment]
I'll merge it, this feature will be tested in the beta (maybe we'll set it to 64 functions if there are problems), and @Mino1289 says he already tried it.

**Comment by FaustinM** [comment]
I'm not very happy with this merge, we cant merge a functionality without any testing...
He didn't test it with 128 functions

**Comment by Lauryy06** [comment]
https://github.com/Lauryy06/Upsilon/pull/28 sets the value to 64, and remember that upsilon-dev is a dev branch, so this feature will be better tested before its release.

**Comment by FaustinM** [comment]
It's a dev branch but we can't test every feature, we can just test everything globally works

**Pull request merged**
